// Static PSX listed companies — used as fallback when DB/API returns no data
export interface PsxStock {
  symbol: string;
  name: string;
  sector: string;
  shariah?: boolean;
}

export const PSX_STOCKS_STATIC: PsxStock[] = [
  // Oil & Gas
  { symbol:"OGDC",   name:"Oil & Gas Dev. Co. Ltd",              sector:"Oil & Gas Exploration" },
  { symbol:"PPL",    name:"Pakistan Petroleum Limited",           sector:"Oil & Gas Exploration" },
  { symbol:"MARI",   name:"Mari Petroleum Company Limited",       sector:"Oil & Gas Exploration" },
  { symbol:"PSO",    name:"Pakistan State Oil Co. Ltd",           sector:"Oil & Gas Marketing" },
  { symbol:"APL",    name:"Attock Petroleum Limited",             sector:"Oil & Gas Marketing" },
  { symbol:"HASCOL", name:"Hascol Petroleum Limited",             sector:"Oil & Gas Marketing" },
  { symbol:"SNGP",   name:"Sui Northern Gas Pipelines Ltd",       sector:"Gas Distribution" },
  { symbol:"SSGC",   name:"Sui Southern Gas Co. Ltd",             sector:"Gas Distribution" },
  { symbol:"ATRL",   name:"Attock Refinery Limited",              sector:"Oil & Gas Marketing" },
  { symbol:"NRL",    name:"National Refinery Limited",            sector:"Oil & Gas Marketing" },
  { symbol:"PRL",    name:"Pakistan Refinery Limited",            sector:"Oil & Gas Marketing" },
  { symbol:"BYCO",   name:"Byco Petroleum Pakistan Ltd",          sector:"Oil & Gas Marketing" },
  { symbol:"POL",    name:"Pakistan Oilfields Limited",           sector:"Oil & Gas Exploration" },
  { symbol:"PARCO",  name:"Pak-Arab Refinery Limited",            sector:"Oil & Gas Marketing" },
  // Commercial Banks
  { symbol:"HBL",    name:"Habib Bank Limited",                   sector:"Commercial Banks" },
  { symbol:"UBL",    name:"United Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"MCB",    name:"MCB Bank Limited",                     sector:"Commercial Banks" },
  { symbol:"MEBL",   name:"Meezan Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"ABL",    name:"Allied Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"BAFL",   name:"Bank Alfalah Limited",                 sector:"Commercial Banks" },
  { symbol:"BAHL",   name:"Bank AL Habib Limited",                sector:"Commercial Banks" },
  { symbol:"NBP",    name:"National Bank of Pakistan",            sector:"Commercial Banks" },
  { symbol:"BOP",    name:"Bank of Punjab",                       sector:"Commercial Banks" },
  { symbol:"AKBL",   name:"Askari Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"FABL",   name:"Faysal Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"SNBL",   name:"Soneri Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"HMB",    name:"Habib Metropolitan Bank Limited",      sector:"Commercial Banks" },
  { symbol:"JSBL",   name:"JS Bank Limited",                      sector:"Commercial Banks" },
  { symbol:"SILK",   name:"Silkbank Limited",                     sector:"Commercial Banks" },
  { symbol:"SMBL",   name:"Summit Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"BOK",    name:"Bank of Khyber",                       sector:"Commercial Banks" },
  { symbol:"BIPL",   name:"BankIslami Pakistan Limited",          sector:"Commercial Banks" },
  { symbol:"SAMBA",  name:"Samba Bank Limited",                   sector:"Commercial Banks" },
  { symbol:"SCBPL",  name:"Standard Chartered Bank (Pak) Ltd",   sector:"Commercial Banks" },
  { symbol:"KASBB",  name:"KASB Bank Limited",                    sector:"Commercial Banks" },
  { symbol:"SINDH",  name:"Bank Al-Falah Limited (Sindh)",        sector:"Commercial Banks" },
  // Cement
  { symbol:"LUCK",   name:"Lucky Cement Limited",                 sector:"Cement" },
  { symbol:"DGKC",   name:"DG Khan Cement Co. Limited",           sector:"Cement" },
  { symbol:"CHCC",   name:"Cherat Cement Co. Limited",            sector:"Cement" },
  { symbol:"FCCL",   name:"Fauji Cement Co. Limited",             sector:"Cement" },
  { symbol:"MLCF",   name:"Maple Leaf Cement Factory Ltd",        sector:"Cement" },
  { symbol:"BWCL",   name:"Bestway Cement Limited",               sector:"Cement" },
  { symbol:"PIOC",   name:"Pioneer Cement Limited",               sector:"Cement" },
  { symbol:"ACPL",   name:"Attock Cement (Pakistan) Limited",     sector:"Cement" },
  { symbol:"POWER",  name:"Kot Addu Power Company Limited",       sector:"Power Gen." },
  { symbol:"KOHC",   name:"Kohat Cement Company Limited",         sector:"Cement" },
  { symbol:"GWLC",   name:"Gharibwal Cement Limited",             sector:"Cement" },
  { symbol:"FLYNG",  name:"Flying Cement Company Limited",        sector:"Cement" },
  { symbol:"THCCL",  name:"Thatta Cement Co. Limited",            sector:"Cement" },
  { symbol:"JVDC",   name:"Javedan Cement Limited",               sector:"Cement" },
  // Fertilizer
  { symbol:"FFC",    name:"Fauji Fertilizer Company Limited",     sector:"Fertilizer" },
  { symbol:"EFERT",  name:"Engro Fertilizers Limited",            sector:"Fertilizer" },
  { symbol:"ENGRO",  name:"Engro Corporation Limited",            sector:"Fertilizer" },
  { symbol:"FATIMA", name:"Fatima Fertilizer Co. Limited",        sector:"Fertilizer" },
  { symbol:"FFBL",   name:"Fauji Fertilizer Bin Qasim Ltd",       sector:"Fertilizer" },
  { symbol:"DAWH",   name:"Dawood Hercules Corp. Limited",        sector:"Fertilizer" },
  // Power
  { symbol:"HUBC",   name:"Hub Power Company Limited",            sector:"Power Gen." },
  { symbol:"KAPCO",  name:"Kot Addu Power Co. Limited",           sector:"Power Gen." },
  { symbol:"NCPL",   name:"Nishat Chunian Power Limited",         sector:"Power Gen." },
  { symbol:"KEL",    name:"K-Electric Limited",                   sector:"Power Gen." },
  { symbol:"LALPIR", name:"Lalpir Power Limited",                 sector:"Power Gen." },
  { symbol:"PAKGEN", name:"PakGen Power Limited",                 sector:"Power Gen." },
  { symbol:"RPOWER", name:"Rousch (Pakistan) Power Ltd",          sector:"Power Gen." },
  { symbol:"TSPL",   name:"Triconboston Consulting Corp.",        sector:"Power Gen." },
  { symbol:"NPKL",   name:"Nishat Power Limited",                 sector:"Power Gen." },
  { symbol:"JPGL",   name:"Jamal Power Ltd",                      sector:"Power Gen." },
  { symbol:"SPWL",   name:"Saif Power Limited",                   sector:"Power Gen." },
  { symbol:"UPPL",   name:"United Provident Fund",                sector:"Power Gen." },
  // Pharma
  { symbol:"SEARL",  name:"The Searle Company Limited",           sector:"Pharmaceuticals" },
  { symbol:"ABOT",   name:"Abbott Laboratories (Pak) Ltd",        sector:"Pharmaceuticals" },
  { symbol:"GLAXO",  name:"GlaxoSmithKline (Pakistan) Ltd",       sector:"Pharmaceuticals" },
  { symbol:"FEROZ",  name:"Ferozsons Laboratories Limited",       sector:"Pharmaceuticals" },
  { symbol:"AGP",    name:"AGP Limited",                          sector:"Pharmaceuticals" },
  { symbol:"SANOFI", name:"Sanofi-Aventis Pakistan Limited",      sector:"Pharmaceuticals" },
  { symbol:"IBLHL",  name:"Ibne Hayyan Pharmaceutical Ltd",       sector:"Pharmaceuticals" },
  { symbol:"HINOPAK",name:"Hinopak Motors Limited",               sector:"Pharmaceuticals" },
  { symbol:"HIMONT", name:"Himont Limited",                       sector:"Pharmaceuticals" },
  { symbol:"PFIZER", name:"Pfizer Pakistan Limited",              sector:"Pharmaceuticals" },
  { symbol:"SAPL",   name:"Siddiqsons Ltd",                       sector:"Pharmaceuticals" },
  // Technology
  { symbol:"SYS",    name:"Systems Limited",                      sector:"Technology" },
  { symbol:"TRG",    name:"TRG Pakistan Limited",                 sector:"Technology" },
  { symbol:"NETSOL", name:"NetSol Technologies Inc.",             sector:"Technology" },
  { symbol:"AVN",    name:"Avanceon Limited",                     sector:"Technology" },
  { symbol:"TELE",   name:"Telecard Limited",                     sector:"Telecom" },
  { symbol:"WTL",    name:"WorldCall Telecom Limited",            sector:"Telecom" },
  { symbol:"PTC",    name:"Pakistan Telecommunication Co. Ltd",   sector:"Telecom" },
  { symbol:"PTCL",   name:"Pakistan Telecom Co. Limited",         sector:"Telecom" },
  // Automobile
  { symbol:"PSMC",   name:"Pak Suzuki Motor Co. Ltd",             sector:"Automobile" },
  { symbol:"INDU",   name:"Indus Motor Company Limited",          sector:"Automobile" },
  { symbol:"HCAR",   name:"Honda Atlas Cars (Pakistan) Ltd",      sector:"Automobile" },
  { symbol:"ATLH",   name:"Atlas Honda Limited",                  sector:"Automobile" },
  { symbol:"GHNI",   name:"Ghandhara Nissan Limited",             sector:"Automobile" },
  { symbol:"GHDNI",  name:"Ghandhara Industries Limited",         sector:"Automobile" },
  { symbol:"MTL",    name:"Millat Tractors Limited",              sector:"Automobile" },
  { symbol:"MZTL",   name:"Masteel Limited",                      sector:"Automobile" },
  { symbol:"TATM",   name:"Tata (Pakistan) Limited",              sector:"Automobile" },
  // Textiles
  { symbol:"NML",    name:"Nishat Mills Limited",                 sector:"Textile" },
  { symbol:"NCL",    name:"Nishat Chunian Limited",               sector:"Textile" },
  { symbol:"KTML",   name:"Kohinoor Textile Mills Limited",       sector:"Textile" },
  { symbol:"CRTM",   name:"Crescent Textile Mills Limited",       sector:"Textile" },
  { symbol:"BWHL",   name:"Bannu Woollen Mills Limited",          sector:"Textile" },
  { symbol:"LOADS",  name:"Loads Limited",                        sector:"Textile" },
  { symbol:"GHCL",   name:"Gulshan Spinning Mills Limited",       sector:"Textile" },
  { symbol:"QUICE",  name:"Quice Food Industries",                sector:"Textile" },
  { symbol:"TREET",  name:"Treet Corporation Limited",            sector:"Textile" },
  { symbol:"SALFI",  name:"Salfi Textile Mills Limited",          sector:"Textile" },
  { symbol:"YOUW",   name:"Younus Textile Mills Limited",         sector:"Textile" },
  { symbol:"GATM",   name:"Gul Ahmed Textile Mills Limited",      sector:"Textile" },
  { symbol:"AMTEX",  name:"Amtex Limited",                        sector:"Textile" },
  { symbol:"ARPL",   name:"Artistic Fabric Mills Ltd",            sector:"Textile" },
  { symbol:"AZAM",   name:"Azam Textile Mills Limited",           sector:"Textile" },
  { symbol:"BHANERO",name:"Bhanero Textile Mills Limited",        sector:"Textile" },
  { symbol:"BURSHANE",name:"Burshane LPG (Pakistan) Ltd",         sector:"Textile" },
  { symbol:"CMSF",   name:"Chenab Limited",                       sector:"Textile" },
  { symbol:"COLG",   name:"Colgate-Palmolive (Pakistan) Ltd",     sector:"FMCG" },
  { symbol:"DTML",   name:"Dewan Textile Mills Limited",          sector:"Textile" },
  { symbol:"EXIDE",  name:"Exide Pakistan Limited",               sector:"Textile" },
  { symbol:"FAISAL", name:"Faisal Spinning Mills Limited",        sector:"Textile" },
  { symbol:"FIBLM",  name:"Firoze Textile Mills Limited",         sector:"Textile" },
  { symbol:"GFIL",   name:"Globe Faisalabad Industries Ltd",      sector:"Textile" },
  { symbol:"HAJRA",  name:"Hajra Textile Mills Limited",          sector:"Textile" },
  { symbol:"HINO",   name:"Hira Textile Mills Limited",           sector:"Textile" },
  { symbol:"ICIL",   name:"Ibrahim Chadha Industries Limited",    sector:"Textile" },
  { symbol:"IDRT",   name:"Ideal Real Estate Pvt Ltd",            sector:"Real Estate" },
  { symbol:"ITTEFAQ",name:"Ittefaq Iron Industries Limited",      sector:"Steel" },
  // Chemical / Industrial
  { symbol:"ICI",    name:"ICI Pakistan Limited",                 sector:"Chemical" },
  { symbol:"LOTCHEM",name:"Lotte Chemical Pakistan Limited",      sector:"Chemical" },
  { symbol:"SITARA", name:"Sitara Chemical Industries Ltd",       sector:"Chemical" },
  { symbol:"NRSL",   name:"National Refinery-Solvents Ltd",       sector:"Chemical" },
  { symbol:"PCAL",   name:"Pakistan Cables Limited",              sector:"Cable & Electrical" },
  { symbol:"PAEL",   name:"Pakistan Elektron Limited",            sector:"Electrical" },
  { symbol:"EPCL",   name:"Engro Polymer & Chemicals Ltd",        sector:"Chemical" },
  // Insurance
  { symbol:"JLICL",  name:"Jubilee Life Insurance Co. Ltd",       sector:"Insurance" },
  { symbol:"JUBILEE",name:"Jubilee General Insurance Co. Ltd",    sector:"Insurance" },
  { symbol:"EFU",    name:"EFU General Insurance Limited",        sector:"Insurance" },
  { symbol:"EFUG",   name:"EFU Life Assurance Ltd",               sector:"Insurance" },
  { symbol:"ADAMJEE",name:"Adamjee Insurance Co. Limited",        sector:"Insurance" },
  { symbol:"UIC",    name:"United Insurance Co. of Pakistan Ltd", sector:"Insurance" },
  { symbol:"IGI",    name:"IGI Life Insurance Limited",           sector:"Insurance" },
  { symbol:"PKIC",   name:"Pak Kuwait Takaful Co. Limited",       sector:"Insurance" },
  { symbol:"SGIC",   name:"SG Insurance Limited",                 sector:"Insurance" },
  // Steel / Engineering
  { symbol:"MUGHAL", name:"Mughal Iron & Steel Industries Ltd",   sector:"Steel" },
  { symbol:"ISL",    name:"International Steels Limited",         sector:"Steel" },
  { symbol:"ASL",    name:"Aisha Steel Mills Limited",            sector:"Steel" },
  { symbol:"ASTL",   name:"Agha Steel Industries Limited",        sector:"Steel" },
  { symbol:"AMSL",   name:"Aman Steel Melting Limited",           sector:"Steel" },
  { symbol:"CSAP",   name:"C.S. Advanced Pakistan Limited",       sector:"Engineering" },
  // FMCG / Food
  { symbol:"NESTLE", name:"Nestlé Pakistan Limited",              sector:"FMCG" },
  { symbol:"UNILEVER",name:"Unilever Pakistan Limited",           sector:"FMCG" },
  { symbol:"PGC",    name:"Procter & Gamble Pakistan Ltd",        sector:"FMCG" },
  { symbol:"CLCPS",  name:"Clover Pakistan Limited",              sector:"FMCG" },
  { symbol:"PNSC",   name:"Pakistan National Shipping Corp.",     sector:"Transport" },
  { symbol:"UNITY",  name:"Unity Foods Limited",                  sector:"FMCG" },
  { symbol:"ATBA",   name:"Al-Abbas Sugar Mills Limited",         sector:"Sugar" },
  { symbol:"AABS",   name:"Al-Abbas Sugar Mills Limited",         sector:"Sugar" },
  { symbol:"AASM",   name:"Al-Abid Silk Mills Limited",           sector:"Sugar" },
  { symbol:"AATM",   name:"Ali Asghar Textile Mills Limited",     sector:"Textile" },
  { symbol:"786",    name:"786 Investments Limited",              sector:"Investments" },
  // Modarabas / Investment
  { symbol:"JSCL",   name:"JS Investments Limited",               sector:"Investments" },
  { symbol:"PIAHCLA",name:"Pakistan Int. Airlines Corp.",         sector:"Transport" },
  // ETFs
  { symbol:"ACIETF", name:"Alfalah Consumer Index ETF",           sector:"ETFs" },
  { symbol:"MIIETF", name:"Mahaana Islamic Index ETF",            sector:"ETFs" },
  { symbol:"NBPGETF",name:"NBP Pakistan Growth ETF",              sector:"ETFs" },
  { symbol:"PACKETF",name:"PACK ETF",                             sector:"ETFs" },
  { symbol:"NIFTYETF",name:"Nifty ETF",                           sector:"ETFs" },
  // More stocks
  { symbol:"AGTL",   name:"Al-Ghazi Tractors Limited",            sector:"Automobile" },
  { symbol:"AHCL",   name:"Arif Habib Corporation Limited",       sector:"Investments" },
  { symbol:"AHSL",   name:"Arif Habib Limited",                   sector:"Brokerage" },
  { symbol:"AICL",   name:"Adamjee Insurance Company Limited",    sector:"Insurance" },
  { symbol:"AIMS",   name:"Al-Meezan Investment Mgmt Ltd",        sector:"Investments" },
  { symbol:"AIRLINK",name:"AirLink Communication Limited",        sector:"Technology" },
  { symbol:"AKDHL",  name:"AKD Holdings Limited",                 sector:"Investments" },
  { symbol:"ALCM",   name:"Al-Caravan Cement Ltd",                sector:"Cement" },
  { symbol:"ALIFE",  name:"Al-Ameen Islamic Savings Fund",        sector:"Insurance" },
  { symbol:"ALTN",   name:"Alton Holdings Limited",               sector:"Investments" },
  { symbol:"AMBL",   name:"Amin Mohammad Bashir Limited",         sector:"Textile" },
  { symbol:"AMCL",   name:"Amtex Limited",                        sector:"Textile" },
  { symbol:"AMDL",   name:"Al-Moiz Dairy",                        sector:"Food" },
  { symbol:"AMEN",   name:"Amen Pharmaceutical",                  sector:"Pharmaceuticals" },
  { symbol:"AMPSL",  name:"Amreli Steels Limited",                sector:"Steel" },
  { symbol:"ANL",    name:"Alfalah GHP Investment Management",    sector:"Investments" },
  { symbol:"ANSS",   name:"Ansari Sugar Mills Ltd",               sector:"Sugar" },
  { symbol:"ANPL",   name:"Anaesthesia Limited",                  sector:"Pharmaceuticals" },
  { symbol:"AOSL",   name:"Al Omer Laminators Ltd",               sector:"Textile" },
  { symbol:"APF",    name:"Arif Habib Fund",                      sector:"ETFs" },
  { symbol:"ATBA",   name:"Atlas Battery Limited",                sector:"Electrical" },
  { symbol:"ATLH",   name:"Atlas Honda Limited",                  sector:"Automobile" },
  { symbol:"ATSL",   name:"Atlas Insurance Limited",              sector:"Insurance" },
  { symbol:"BAPL",   name:"Baluchistan Particle Board Limited",   sector:"Wood & Boards" },
  { symbol:"BCML",   name:"Bawany Air Products Limited",          sector:"Chemical" },
  { symbol:"BECO",   name:"Beacon Energy Limited",                sector:"Power Gen." },
  { symbol:"BELA",   name:"Beaconhouse School Limited",           sector:"Education" },
  { symbol:"BESTML", name:"Bestway Logistics",                    sector:"Logistics" },
  { symbol:"BIFO",   name:"Bi-Folkal Optics Pvt Ltd",             sector:"Technology" },
  { symbol:"BIMCO",  name:"Bimco Pakistan Limited",               sector:"Chemical" },
  { symbol:"BML",    name:"Burshane Pakistan Limited",            sector:"LPG" },
  { symbol:"BOP",    name:"The Bank of Punjab",                   sector:"Commercial Banks" },
  { symbol:"BSL",    name:"Bawany Sugar Mills Limited",           sector:"Sugar" },
  { symbol:"BTPL",   name:"Broad Peak Investments Limited",       sector:"Investments" },
  { symbol:"CAPD",   name:"Capital Fund",                         sector:"ETFs" },
  { symbol:"CAVEL",  name:"Cavmont Capital Holdings",             sector:"Investments" },
  { symbol:"CCBL",   name:"Century Cotton Bleaching Ltd",         sector:"Textile" },
  { symbol:"CCPL",   name:"Central Power Ltd",                    sector:"Power Gen." },
  { symbol:"CEFL",   name:"Century Insurance Ltd",                sector:"Insurance" },
  { symbol:"CEPB",   name:"Cement EPTB Ltd",                      sector:"Cement" },
  { symbol:"CEPCO",  name:"Central Electricity Power Corp.",      sector:"Power Gen." },
  { symbol:"CERP",   name:"CERP Pakistan",                        sector:"Pharmaceutical" },
  { symbol:"CFL",    name:"Century Financial Limited",            sector:"Finance" },
  { symbol:"CFPL",   name:"Coats Pakistan Limited",               sector:"Textile" },
  { symbol:"CJPL",   name:"Continental Ji Ltd",                   sector:"Food" },
  { symbol:"CLAAS",  name:"CLAAS Pakistan Limited",               sector:"Machinery" },
  { symbol:"CLBL",   name:"Chashma Limestone Limited",            sector:"Cement" },
  { symbol:"CMFD",   name:"Clariant Pakistan Limited",            sector:"Chemical" },
  { symbol:"CMPAK",  name:"CM Pak Limited",                       sector:"Telecom" },
  { symbol:"CNERGY", name:"Cnergyico PK Limited",                 sector:"Oil & Gas Marketing" },
  { symbol:"COHC",   name:"Century Paper & Board Mills Ltd",      sector:"Paper & Board" },
  { symbol:"CPPL",   name:"Capital Power Limited",                sector:"Power Gen." },
  { symbol:"CRTM",   name:"Crescent Textile Mills Limited",       sector:"Textile" },
  { symbol:"CSOF",   name:"Continental Software (Pakistan) Ltd",  sector:"Technology" },
  { symbol:"CSUF",   name:"CS Fund Ltd",                          sector:"ETFs" },
  { symbol:"CTM",    name:"Colgate Textile Mills Limited",        sector:"Textile" },
  { symbol:"CWSM",   name:"Cyan Limited",                         sector:"Investments" },
  { symbol:"DALA",   name:"Dala Foods Limited",                   sector:"Food" },
  { symbol:"DANA",   name:"Dana Textile Mills Limited",           sector:"Textile" },
  { symbol:"DAPH",   name:"Dawood Power Limited",                 sector:"Power Gen." },
  { symbol:"DCL",    name:"Dewan Cement Limited",                 sector:"Cement" },
  { symbol:"DCSL",   name:"Dolmen City REIT",                     sector:"Real Estate" },
  { symbol:"DEL",    name:"Dewan Electrical Fans Ltd",            sector:"Engineering" },
  { symbol:"DFML",   name:"Dewan Farooque Motors Ltd",            sector:"Automobile" },
  { symbol:"DGKCI",  name:"D.G. Khan Cement Company Ltd",         sector:"Cement" },
  { symbol:"DGTL",   name:"Digital World Ltd",                    sector:"Technology" },
  { symbol:"DINT",   name:"Dint Industries Limited",              sector:"Manufacturing" },
  { symbol:"DKTM",   name:"Dewan Khalid Textile Mills Ltd",       sector:"Textile" },
  { symbol:"DLL",    name:"Dynea Pakistan Limited",               sector:"Chemical" },
  { symbol:"DLMTL",  name:"Denim Clothing Company Limited",       sector:"Textile" },
  { symbol:"DNH",    name:"DNH Ltd",                              sector:"Real Estate" },
  { symbol:"DOLMEN", name:"Dolmen City REIT",                     sector:"Real Estate" },
  { symbol:"DSL",    name:"Diamond Steel Limited",                sector:"Steel" },
  { symbol:"DTML",   name:"Dewan Textile Mills Limited",          sector:"Textile" },
  { symbol:"DWSM",   name:"Dawlance (Pvt) Ltd",                   sector:"Electronics" },
  { symbol:"ECOP",   name:"ECOPACK Limited",                      sector:"Packaging" },
  { symbol:"EFL",    name:"Engro Foods Limited",                  sector:"Food" },
  { symbol:"EFUG",   name:"EFU Life Assurance Ltd",               sector:"Insurance" },
  { symbol:"ELOAD",  name:"Engro Loads Limited",                  sector:"Fertilizer" },
  { symbol:"ENGROC",  name:"Engro Corp Limited",                   sector:"Fertilizer" },
  { symbol:"EMCO",   name:"Emco Industries Limited",              sector:"Engineering" },
  { symbol:"ENCI",   name:"Engro Chemicals Limited",              sector:"Chemical" },
  { symbol:"EOL",    name:"Elahi Electric Company Limited",       sector:"Engineering" },
  { symbol:"EOSL",   name:"Eastern Oxygen Limited",               sector:"Chemical" },
  { symbol:"EPQL",   name:"Engro Powergen Qadirpur Ltd",          sector:"Power Gen." },
  { symbol:"ESBL",   name:"Eden Sugar & Beverages Limited",       sector:"Sugar" },
  { symbol:"ESML",   name:"Eden Sugar Mills Limited",             sector:"Sugar" },
  { symbol:"FAEL",   name:"Fauji Akbar Portia Fertilizer",        sector:"Fertilizer" },
  { symbol:"FAHC",   name:"Fazal Ahmad & Co. Limited",            sector:"Textile" },
  { symbol:"FALM",   name:"Fecto Belarus Tractors Ltd",           sector:"Automobile" },
  { symbol:"FDL",    name:"Feroze 1888 Mills Limited",            sector:"Textile" },
  { symbol:"FECTC",  name:"Fecto Cement Limited",                 sector:"Cement" },
  { symbol:"FFCE",   name:"FFC Energy Limited",                   sector:"Power Gen." },
  { symbol:"FHAM",   name:"F.H.A.M. Ltd",                         sector:"Textile" },
  { symbol:"FNEL",   name:"Fatima Energy Limited",                sector:"Power Gen." },
  { symbol:"FNHL",   name:"Fazal Naseer Holdings Limited",        sector:"Investments" },
  { symbol:"FOML",   name:"Feroze Mills Limited",                 sector:"Textile" },
  { symbol:"FRSM",   name:"Faisal Spinning Mills Limited",        sector:"Textile" },
  { symbol:"FSD",    name:"Faisalabad Stock Deals",               sector:"Investments" },
  { symbol:"FTBL",   name:"First Treet Bank Limited",             sector:"Commercial Banks" },
  { symbol:"FTML",   name:"Feroze Textile Mills Limited",         sector:"Textile" },
  { symbol:"FWBL",   name:"First Women Bank Limited",             sector:"Commercial Banks" },
  { symbol:"GAGL",   name:"Gul Ahmed Energy Ltd",                 sector:"Power Gen." },
  { symbol:"GAPCO",  name:"Gas Power Company Ltd",                sector:"Power Gen." },
  { symbol:"GGL",    name:"Grand Group Limited",                  sector:"Food" },
  { symbol:"GHL",    name:"Ghani Holdings Limited",               sector:"Glass" },
  { symbol:"GHNI",   name:"Ghandhara Nissan Limited",             sector:"Automobile" },
  { symbol:"GIL",    name:"Ghani Industries Limited",             sector:"Glass" },
  { symbol:"GITL",   name:"Gulshan Textile Mills Limited",        sector:"Textile" },
  { symbol:"GKBL",   name:"Ghalib & Co. Ltd",                     sector:"Textile" },
  { symbol:"GLSL",   name:"Global Securities Pakistan Ltd",       sector:"Brokerage" },
  { symbol:"GMDTL",  name:"Gondal Maize Mills Limited",           sector:"Food" },
  { symbol:"GMNL",   name:"Ghani Minerals Limited",               sector:"Mining" },
  { symbol:"GRAYS",  name:"Grays of Cambridge (Pakistan) Ltd",    sector:"FMCG" },
  { symbol:"GRYL",   name:"Grays Leasing Ltd",                    sector:"Leasing" },
  { symbol:"GTC",    name:"Gulf Texcot Limited",                  sector:"Textile" },
  { symbol:"HABSM",  name:"Habib Sugar Mills Limited",            sector:"Sugar" },
  { symbol:"HAFL",   name:"Habib-ADM Limited",                    sector:"Food" },
  { symbol:"HALF",   name:"HBL Asset Management Ltd",             sector:"Investments" },
  { symbol:"HALS",   name:"Halla Cement Ltd",                     sector:"Cement" },
  { symbol:"HASCOL", name:"Hascol Petroleum Limited",             sector:"Oil & Gas Marketing" },
  { symbol:"HBL",    name:"Habib Bank Limited",                   sector:"Commercial Banks" },
  { symbol:"HCL",    name:"Hunting Creek Limited",                sector:"Investments" },
  { symbol:"HECL",   name:"Hira Electronics Ltd",                 sector:"Electronics" },
  { symbol:"HESBL",  name:"Hira Sugar Mills Ltd",                 sector:"Sugar" },
  { symbol:"HINOPAK",name:"Hinopak Motors Limited",               sector:"Automobile" },
  { symbol:"HIS",    name:"Hill Industries Limited",              sector:"Textile" },
  { symbol:"HLFL",   name:"Habib Land Finance Limited",           sector:"Finance" },
  { symbol:"HNFIN",  name:"HN Finance Limited",                   sector:"Finance" },
  { symbol:"HRML",   name:"Habib Rafiq Limited",                  sector:"Construction" },
  { symbol:"HSML",   name:"Hussain Sugar Mills Ltd",              sector:"Sugar" },
  { symbol:"HTBL",   name:"Haqiqat Textiles Limited",             sector:"Textile" },
  { symbol:"HUBC",   name:"Hub Power Company Limited",            sector:"Power Gen." },
  { symbol:"HUMNL",  name:"Human Resource Mining Corp.",          sector:"Mining" },
  { symbol:"ICL",    name:"International Capsule Ltd",            sector:"Pharmaceuticals" },
  { symbol:"ILP",    name:"International Leasing Pakistan Ltd",   sector:"Leasing" },
  { symbol:"IMC",    name:"Indus Motor Co. Limited",              sector:"Automobile" },
  { symbol:"IMSL",   name:"Idrees Manufacturing & Spinning",      sector:"Textile" },
  { symbol:"INDU",   name:"Indus Motor Company Limited",          sector:"Automobile" },
  { symbol:"IPAK",   name:"International Packaging Films Ltd",    sector:"Paper & Board" },
  { symbol:"IQBL",   name:"Iqbal Spinning Mills Limited",         sector:"Textile" },
  { symbol:"IRBL",   name:"Ibrahim Realty Limited",               sector:"Real Estate" },
  { symbol:"ISIL",   name:"International Sugar Industries Ltd",   sector:"Sugar" },
  { symbol:"ISL",    name:"International Steels Limited",         sector:"Steel" },
  { symbol:"JACL",   name:"Jauharabad Cement Limited",            sector:"Cement" },
  { symbol:"JAFF",   name:"Jaffar Brothers Limited",              sector:"Investments" },
  { symbol:"JAHL",   name:"Jahangir Siddiqui & Co. Ltd",          sector:"Brokerage" },
  { symbol:"JBSSL",  name:"JBS Sugar Limited",                    sector:"Sugar" },
  { symbol:"JCSL",   name:"Jafary & Co. (Pakistan) Ltd",          sector:"Textile" },
  { symbol:"JDWS",   name:"J.D.W. Sugar Mills Limited",           sector:"Sugar" },
  { symbol:"JKML",   name:"JK Spinning Mills Limited",            sector:"Textile" },
  { symbol:"JLICL",  name:"Jubilee Life Insurance Co. Ltd",       sector:"Insurance" },
  { symbol:"JPPHM",  name:"JoPak Pharma Limited",                 sector:"Pharmaceuticals" },
  { symbol:"JSBL",   name:"JS Bank Limited",                      sector:"Commercial Banks" },
  { symbol:"JSCL",   name:"JS Investments Limited",               sector:"Investments" },
  { symbol:"JSML",   name:"J.S. Spinning Mills Limited",          sector:"Textile" },
  { symbol:"JTMF",   name:"Janana de Malucho Textile Mills Ltd",  sector:"Textile" },
  { symbol:"JVDC",   name:"Javedan Corporation Limited",          sector:"Cement" },
  { symbol:"KAEL",   name:"K-Electric Ltd",                       sector:"Power Gen." },
  { symbol:"KAPCO",  name:"Kot Addu Power Co. Limited",           sector:"Power Gen." },
  { symbol:"KASBSM", name:"KASB Modaraba",                        sector:"Modarabas" },
  { symbol:"KBSM",   name:"Khurshid Spinning Mills Ltd",          sector:"Textile" },
  { symbol:"KDL",    name:"Kohinoor Dairies Limited",             sector:"Food" },
  { symbol:"KEPL",   name:"Koh-e-Noor Energy Ltd",                sector:"Power Gen." },
  { symbol:"KFL",    name:"Kohinoor Fertilizer Limited",          sector:"Fertilizer" },
  { symbol:"KFSL",   name:"Kausar Finance & Leasing Ltd",         sector:"Finance" },
  { symbol:"KG",     name:"Karachi Gas & Chemicals Ltd",          sector:"Gas Distribution" },
  { symbol:"KJCL",   name:"Kinetics & Joinery Co. Ltd",           sector:"Engineering" },
  { symbol:"KML",    name:"Kohinoor Mills Limited",               sector:"Textile" },
  { symbol:"KMPK",   name:"K&M Pakistan Limited",                 sector:"Electronics" },
  { symbol:"KNTM",   name:"Kohinoor Textile Mills Limited",       sector:"Textile" },
  { symbol:"KOHE",   name:"Kohat Cement Company Limited",         sector:"Cement" },
  { symbol:"KSB",    name:"KSB Pumps Company Limited",            sector:"Engineering" },
  { symbol:"KTML",   name:"Kohinoor Textile Mills Limited",       sector:"Textile" },
  { symbol:"LGYL",   name:"Lotte Chemical PakIstan Limited",      sector:"Chemical" },
  { symbol:"LHG",    name:"Lucky Holdings Limited",               sector:"Investments" },
  { symbol:"LIIM",   name:"Lucky Investments Ltd",                sector:"Investments" },
  { symbol:"LINFL",  name:"Linde Pakistan Limited",               sector:"Chemical" },
  { symbol:"LMKT",   name:"Lakson Tobacco Co. Limited",           sector:"Tobacco" },
  { symbol:"LNKL",   name:"Lucky Network & Telecom Ltd",          sector:"Telecom" },
  { symbol:"LTC",    name:"Leiner Pakistan Limited",              sector:"Pharmaceuticals" },
  { symbol:"LUCK",   name:"Lucky Cement Limited",                 sector:"Cement" },
  { symbol:"LUMSS",  name:"Lums Scholar Fund",                    sector:"ETFs" },
  { symbol:"MACFL",  name:"Macpac Films Limited",                 sector:"Packaging" },
  { symbol:"MAHL",   name:"Masood Holdings Limited",              sector:"Textile" },
  { symbol:"MAPL",   name:"M.A. Pakistan Ltd",                    sector:"Textile" },
  { symbol:"MARI",   name:"Mari Petroleum Company Limited",       sector:"Oil & Gas Exploration" },
  { symbol:"MASM",   name:"Mamon Sugar Mills Limited",            sector:"Sugar" },
  { symbol:"MATPL",  name:"Matrix Pakistan Limited",              sector:"Pharmaceutical" },
  { symbol:"MCB",    name:"MCB Bank Limited",                     sector:"Commercial Banks" },
  { symbol:"MCBAH",  name:"MCB-Arif Habib Savings & Investments", sector:"Investments" },
  { symbol:"MDTL",   name:"Madina Textile Mills Limited",         sector:"Textile" },
  { symbol:"MEBL",   name:"Meezan Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"MERIT",  name:"Merit Packaging Limited",              sector:"Packaging" },
  { symbol:"MFFL",   name:"Maple Leaf Factories Limited",         sector:"Cement" },
  { symbol:"MFPL",   name:"Mayfair Foods Limited",                sector:"Food" },
  { symbol:"MGMC",   name:"M.G. Milk Collection Ltd",             sector:"Food" },
  { symbol:"MHFL",   name:"Mahindra & Mahindra Financial Ltd",    sector:"Finance" },
  { symbol:"MIIETF", name:"Mahaana Islamic Index ETF",            sector:"ETFs" },
  { symbol:"MISM",   name:"Mirpurkhas Sugar Mills Ltd",           sector:"Sugar" },
  { symbol:"MJL",    name:"Millat Jack Limited",                  sector:"Engineering" },
  { symbol:"MLCF",   name:"Maple Leaf Cement Factory Ltd",        sector:"Cement" },
  { symbol:"MNKT",   name:"Manketti Holdings Limited",            sector:"Investments" },
  { symbol:"MONFL",  name:"Mon-Fri Holdings Limited",             sector:"Investments" },
  { symbol:"MPL",    name:"Mega Paks Limited",                    sector:"Packaging" },
  { symbol:"MRPT",   name:"Maqbool Textile Mills Limited",        sector:"Textile" },
  { symbol:"MTL",    name:"Millat Tractors Limited",              sector:"Automobile" },
  { symbol:"MUGHAL", name:"Mughal Iron & Steel Industries Ltd",   sector:"Steel" },
  { symbol:"NBL",    name:"National Bank Limited",                sector:"Commercial Banks" },
  { symbol:"NBP",    name:"National Bank of Pakistan",            sector:"Commercial Banks" },
  { symbol:"NCCPL",  name:"National Clearing Company Pak Ltd",    sector:"Financial Services" },
  { symbol:"NCPL",   name:"Nishat Chunian Power Limited",         sector:"Power Gen." },
  { symbol:"NESTLE", name:"Nestle Pakistan Limited",              sector:"Food" },
  { symbol:"NETSOL", name:"NetSol Technologies Inc.",             sector:"Technology" },
  { symbol:"NICE",   name:"NICE Holdings Limited",                sector:"Investments" },
  { symbol:"NIRM",   name:"Nishat Renewable Energy Ltd",          sector:"Power Gen." },
  { symbol:"NML",    name:"Nishat Mills Limited",                 sector:"Textile" },
  { symbol:"NRL",    name:"National Refinery Limited",            sector:"Oil & Gas Marketing" },
  { symbol:"NRTC",   name:"Northern Resources Technologies Ltd",  sector:"Technology" },
  { symbol:"NSL",    name:"Nagina Cotton Mills Ltd",              sector:"Textile" },
  { symbol:"NTCL",   name:"National Textile Corporation Ltd",     sector:"Textile" },
  { symbol:"OIC",    name:"Orient Insurance Company Ltd",         sector:"Insurance" },
  { symbol:"OML",    name:"Olympia Modaraba",                     sector:"Modarabas" },
  { symbol:"OPFL",   name:"Optimum Pharma Ltd",                   sector:"Pharmaceuticals" },
  { symbol:"ORIX",   name:"ORIX Leasing Pakistan Limited",        sector:"Leasing" },
  { symbol:"PACE",   name:"Pace (Pakistan) Limited",              sector:"Real Estate" },
  { symbol:"PACRA",  name:"Pakistan Credit Rating Agency Ltd",    sector:"Financial Services" },
  { symbol:"PAEL",   name:"Pakistan Elektron Limited",            sector:"Engineering" },
  { symbol:"PAKD",   name:"Pak Datacom Limited",                  sector:"Technology" },
  { symbol:"PAKL",   name:"PAK LNG Terminal Ltd",                 sector:"Gas Distribution" },
  { symbol:"PAKRI",  name:"Pak Reinsurance Co. Limited",          sector:"Insurance" },
  { symbol:"PAKT",   name:"Pakhtunkhwa Textile Mills Ltd",        sector:"Textile" },
  { symbol:"PAL",    name:"Pakistan Aluminium Beverages Can Ltd", sector:"Packaging" },
  { symbol:"PANGAS", name:"Pakistan Industrial Gas Ltd",          sector:"Chemical" },
  { symbol:"PCAL",   name:"Pakistan Cables Limited",              sector:"Cable & Electrical" },
  { symbol:"PCFL",   name:"Pakistan Capital Fund Ltd",            sector:"ETFs" },
  { symbol:"PEHLA",  name:"Pehla Investments Limited",            sector:"Investments" },
  { symbol:"PGC",    name:"Procter & Gamble Pakistan Ltd",        sector:"FMCG" },
  { symbol:"PIAHCLA",name:"Pakistan Int. Airlines Corp.",         sector:"Transport" },
  { symbol:"PIBTL",  name:"Pioneer Cement Limited",               sector:"Cement" },
  { symbol:"PIOC",   name:"Pioneer Cement Limited",               sector:"Cement" },
  { symbol:"PIR",    name:"Pak I.D.S. Ltd",                       sector:"Textile" },
  { symbol:"PKGP",   name:"Pakistan Gas & Power Ltd",             sector:"Power Gen." },
  { symbol:"PKGS",   name:"Packages Limited",                     sector:"Paper & Board" },
  { symbol:"PMIC",   name:"Pakistan Microfinance Investment Co.", sector:"Finance" },
  { symbol:"PML",    name:"Philip Morris (Pakistan) Ltd",         sector:"Tobacco" },
  { symbol:"PMPK",   name:"Pakistan Marble Mining Co. Ltd",       sector:"Mining" },
  { symbol:"PNSC",   name:"Pakistan National Shipping Corp.",     sector:"Transport" },
  { symbol:"POL",    name:"Pakistan Oilfields Limited",           sector:"Oil & Gas Exploration" },
  { symbol:"PPL",    name:"Pakistan Petroleum Limited",           sector:"Oil & Gas Exploration" },
  { symbol:"PPTL",   name:"Packages Paper Products Ltd",          sector:"Paper & Board" },
  { symbol:"PRET",   name:"Pakistan Refinery Limited",            sector:"Oil & Gas Marketing" },
  { symbol:"PRL",    name:"Pakistan Refinery Limited",            sector:"Oil & Gas Marketing" },
  { symbol:"PSO",    name:"Pakistan State Oil Co. Ltd",           sector:"Oil & Gas Marketing" },
  { symbol:"PSMC",   name:"Pak Suzuki Motor Co. Ltd",             sector:"Automobile" },
  { symbol:"PTC",    name:"Pakistan Telecommunication Co. Ltd",   sector:"Telecom" },
  { symbol:"PTCL",   name:"Pakistan Telecom Co. Limited",         sector:"Telecom" },
  { symbol:"PTPL",   name:"ProTechno Pakistan Limited",           sector:"Technology" },
  { symbol:"QUICE",  name:"Quice Food Industries Limited",        sector:"Food" },
  { symbol:"RAFM",   name:"Rafhan Maize Products Co. Ltd",        sector:"Food" },
  { symbol:"RECL",   name:"Reckitt Benckiser Pakistan Ltd",       sector:"FMCG" },
  { symbol:"RMPL",   name:"Ravi Melting Pvt Ltd",                 sector:"Steel" },
  { symbol:"RPL",    name:"Rupali Polyester Limited",             sector:"Textile" },
  { symbol:"RUBY",   name:"Ruby Textile Mills Limited",           sector:"Textile" },
  { symbol:"SAFL",   name:"Salar Fertilizer Limited",             sector:"Fertilizer" },
  { symbol:"SAPM",   name:"Sapphire Fibers Limited",              sector:"Textile" },
  { symbol:"SARB",   name:"Sarbar Minerals Limited",              sector:"Mining" },
  { symbol:"SCBPL",  name:"Standard Chartered Bank (Pakistan)",   sector:"Commercial Banks" },
  { symbol:"SCLL",   name:"Siemens (Pakistan) Engineering Co.",   sector:"Engineering" },
  { symbol:"SEARL",  name:"The Searle Company Limited",           sector:"Pharmaceuticals" },
  { symbol:"SFFL",   name:"Salfi Textile Mills Limited",          sector:"Textile" },
  { symbol:"SGML",   name:"Southern Gas Ltd",                     sector:"Gas Distribution" },
  { symbol:"SILK",   name:"Silkbank Limited",                     sector:"Commercial Banks" },
  { symbol:"SITARA", name:"Sitara Chemical Industries Ltd",       sector:"Chemical" },
  { symbol:"SLCL",   name:"Saudi Leasing Co. Limited",            sector:"Leasing" },
  { symbol:"SLML",   name:"Siddiqsons Limited",                   sector:"Textile" },
  { symbol:"SMBL",   name:"Summit Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"SMCPL",  name:"SMC Pakistan Limited",                 sector:"Brokerage" },
  { symbol:"SNBL",   name:"Soneri Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"SNGP",   name:"Sui Northern Gas Pipelines Ltd",       sector:"Gas Distribution" },
  { symbol:"SPWL",   name:"Saif Power Limited",                   sector:"Power Gen." },
  { symbol:"SSGC",   name:"Sui Southern Gas Co. Ltd",             sector:"Gas Distribution" },
  { symbol:"SSL",    name:"Schazoo Pharma Limited",               sector:"Pharmaceuticals" },
  { symbol:"STCL",   name:"Synthetic Products Enterprises Ltd",   sector:"Textile" },
  { symbol:"STML",   name:"Shadman Cotton Mills Limited",         sector:"Textile" },
  { symbol:"SYS",    name:"Systems Limited",                      sector:"Technology" },
  { symbol:"TELE",   name:"Telecard Limited",                     sector:"Telecom" },
  { symbol:"TGL",    name:"Trans Gulf Limited",                   sector:"Leasing" },
  { symbol:"THALL",  name:"Thal Limited",                         sector:"Engineering" },
  { symbol:"THCCL",  name:"Thatta Cement Co. Limited",            sector:"Cement" },
  { symbol:"TPML",   name:"Tri-Pack Films Limited",               sector:"Packaging" },
  { symbol:"TREET",  name:"Treet Corporation Limited",            sector:"Textile" },
  { symbol:"TRG",    name:"TRG Pakistan Limited",                 sector:"Technology" },
  { symbol:"TSPL",   name:"Triconboston Consulting Corp.",        sector:"Power Gen." },
  { symbol:"TTML",   name:"Taj Textile Mills Limited",            sector:"Textile" },
  { symbol:"UBL",    name:"United Bank Limited",                  sector:"Commercial Banks" },
  { symbol:"UIC",    name:"United Insurance Co. of Pakistan Ltd", sector:"Insurance" },
  { symbol:"UNITY",  name:"Unity Foods Limited",                  sector:"Food" },
  { symbol:"UPFL",   name:"United Provinces Foods Limited",       sector:"Food" },
  { symbol:"VARELI", name:"Vareli Fabrics Limited",               sector:"Textile" },
  { symbol:"WAHN",   name:"Wahid Industries Limited",             sector:"Textile" },
  { symbol:"WNBL",   name:"Winkbud Limited",                      sector:"Investments" },
  { symbol:"WTL",    name:"WorldCall Telecom Limited",            sector:"Telecom" },
  { symbol:"YOUW",   name:"Younus Textile Mills Limited",         sector:"Textile" },
  { symbol:"ZIL",    name:"Zeal Pakistan Limited",                sector:"Textile" },
  { symbol:"ZSSL",   name:"Zorays Solar Pakistan Limited",        sector:"Power Gen." },
];

// Deduplicated list (first occurrence of each symbol wins)
const _seen = new Set<string>();
export const PSX_STOCKS: PsxStock[] = PSX_STOCKS_STATIC.filter(s => {
  if (_seen.has(s.symbol)) return false;
  _seen.add(s.symbol);
  return true;
});

export function searchPsxStocks(query: string, limit = 50): PsxStock[] {
  if (!query) return PSX_STOCKS.slice(0, limit);
  const q = query.toLowerCase();
  return PSX_STOCKS.filter(
    s => s.symbol.toLowerCase().startsWith(q) || s.name.toLowerCase().includes(q)
  ).slice(0, limit);
}
